### ISSUE TITLE
Add dry-run mode

### ISSUE THREAD

**Issue by ziima** [akolpakov/django-unused-media#13]
It would be very helpful if the command would have a dry-run mode.

**Comment by akolpakov** [comment]
There is `dry-run` mode. Maybe not so obvious. But if you run `./manage.py cleanup_unused_media` in interactive mode (default) it will show you what will be removed and ask you confirmation.

What is your suggestion, to add `--dry-run` option?

**Comment by ziima** [comment]
The problem is, that the interactive mode will remain hanging. The `dry-run` should just print the files and quit without a requirement of user input.
