### ISSUE TITLE
--noinput does not work as expected

### ISSUE THREAD

**Issue by saily** [akolpakov/django-unused-media#3]
Hi, 

when adding `--noinput` to management command it still asks if we want to remove following items:

    $ .../manage.py  cleanup_unused_media --noinput
    These files will be deleted:
    screenshots/Screen_Shot_2017-01-16_at_10.56.29.png
    Are you sure you want to remove 1 unused files? (Y/n)

Btw, i'm using Django 1.10.5 and Python 2.7.5.

**Comment by akolpakov** [comment]
Fixed in v0.1.6, please update

**Comment by saily** [comment]
great, thank you!
