### ISSUE TITLE
missing pip version 0.1.13

### ISSUE THREAD

**Issue by mtazzari** [akolpakov/django-unused-media#30]
I am having troubles installing version 0.1.13. 
If I do `pip install django-unused-media` I get version 0.1.12 installed.
If I specify the version explictly, I get the following error:
```bash
$ pip install django-unused-media==0.1.13
Collecting django-unused-media==0.1.13
  Could not find a version that satisfies the requirement django-unused-media==0.1.13 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12)
No matching distribution found for django-unused-media==0.1.13
```

**Comment by akolpakov** [comment]
Seems that new package loader `twine` requires to upload two different packages for py2 or py3.

Please try again. Now both versions were uploaded

**Comment by mtazzari** [comment]
Great, now it works. Many thanks for the quick fix!
