### ISSUE TITLE
Media is treated as unused if filtered from the default manager

### ISSUE THREAD

**Issue by tari** [akolpakov/django-unused-media#35]
I have a model on which the default manager filters out some instances, which causes the media matching the filtered rows to be treated as unused. This is problematic.

Using [`_base_manager` rather than `objects`](https://docs.djangoproject.com/en/3.0/topics/db/managers/#base-managers) to find model instances should fix this problem, and it fixes the potential bug around assuming that every model has a default manager called `objects`.

**Comment by akolpakov** [comment]
Will be released in new version 0.2
