### ISSUE TITLE
Default action should be uppercase

### ISSUE THREAD

**Issue by saily** [akolpakov/django-unused-media#4]
Action triggered by hitting Enter without input should be uppercase, which should show uppercase `N` instead of `Y`. 

As is:

	$ .../manage.py  cleanup_unused_media
	These files will be deleted:
	screenshots/Screen_Shot_2017-01-16_at_10.56.29.png
	Are you sure you want to remove 1 unused files? (Y/n)

Should be:

	$ .../manage.py  cleanup_unused_media
	These files will be deleted:
	screenshots/Screen_Shot_2017-01-16_at_10.56.29.png
	Are you sure you want to remove 1 unused files? (y/N)

**Comment by akolpakov** [comment]
What is the reason behind?
Reason to have `(Y/n)` is that `shift + y` prevent from occasionally deleting more than just `y` 

For deleting without confirmation, please use `--noinput` flag

**Comment by saily** [comment]
default uppercase is what *nix users expect.

**Comment by akolpakov** [comment]
Fixed. Will be in future versions
